### ISSUE TITLE
Bot not joining channel when Config is changed

### ISSUE THREAD

**Issue by saloun** [rmmh/skybot#137]
For some reason when i execute the start command the bot connects to the IRC network, but does not join 2channels i added on Config.

Note that i can use commands via PM to Bot, but i want the bot on my channel.

Regards, Saloun.

**Comment by javaj0hn** [comment]
Are you sure you have lxml installed?

**Comment by rmmh** [comment]
Your config should look like:

```
{
  "connections":
  {
    "example irc":
    {
      "server": "irc.example.net",
      "nick": "coolbot",
      "channels": ["#test"]
    }
  }
}
```
